CREATE TABLE IF NOT EXISTS users (
    "id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    "username" TEXT NOT NULL UNIQUE,
    "password" TEXT NOT NULL,
    "email" TEXT NOT NULL,
    "is_active" INTEGER NOT NULL DEFAULT(0)
);
CREATE TABLE IF NOT EXISTS sessions (
    "sid" TEXT NOT NULL UNIQUE,
    "user_id" INTEGER
);
CREATE TABLE IF NOT EXISTS comments(
    "id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    "user_id" INTEGER NOT NULL,
    "comment" TEXT NOT NULL
);
